//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSpaceshipWPF.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_PlanetLinks
    {
        public int Id { get; set; }
        public Nullable<int> Flight_Id { get; set; }
        public Nullable<int> PlanetLink_Id { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual PlanetLinks PlanetLinks { get; set; }
    }
}
