//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSpaceshipWPF.Components
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpaceshipCompanyEntities : DbContext
    {
        public SpaceshipCompanyEntities()
            : base("name=SpaceshipCompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<Flight_PlanetLinks> Flight_PlanetLinks { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Passenger> Passenger { get; set; }
        public virtual DbSet<Passenger_Flight> Passenger_Flight { get; set; }
        public virtual DbSet<Planet> Planet { get; set; }
        public virtual DbSet<PlanetLinks> PlanetLinks { get; set; }
        public virtual DbSet<Spaceship> Spaceship { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trouble_Passenger> Trouble_Passenger { get; set; }
        public virtual DbSet<Trouble_Planet> Trouble_Planet { get; set; }
        public virtual DbSet<Troubles> Troubles { get; set; }
    }
}
