//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSpaceshipWPF.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanetLinks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanetLinks()
        {
            this.Flight_PlanetLinks = new HashSet<Flight_PlanetLinks>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PlanetStart_Id { get; set; }
        public Nullable<int> PlanetEnd_Id { get; set; }
        public Nullable<int> Wearout { get; set; }
        public Nullable<System.DateTimeOffset> Duration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight_PlanetLinks> Flight_PlanetLinks { get; set; }
        public virtual Planet Planet { get; set; }
        public virtual Planet Planet1 { get; set; }
    }
}
