//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSpaceshipWPF.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trouble_Passenger
    {
        public int Id { get; set; }
        public Nullable<int> Trouble_Id { get; set; }
        public Nullable<int> Passenger_Id { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Troubles Troubles { get; set; }
    }
}
